---
title: "CMI-PB - Comparative analysis of prediction models"
author: "Mikkel Niklas Rasmussen"
date: "4/29/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressMessages(library('dplyr'))
suppressMessages(library('tidyr'))
suppressMessages(library("ggplot2"))
suppressMessages(library('tibble'))
suppressMessages(library("corrplot"))
suppressMessages(library("ggrepel"))
suppressMessages(library("zoo"))
suppressMessages(library("lubridate"))


```


## Load results from all of the prediction methods evaluate on the CMI-PB 2020 dataset

```{r}

############  2020 results ############ 
# Study 1 - Avey et al. 2017
load("../Study-1-Avey-2017/Results/2020/Gene_signature/Avey.2017.gene.sig.2020.results.RData")
load("../Study-1-Avey-2017/Results/2020/M54/Avey.2017.module.M54.2020.results.RData")
load("../Study-1-Avey-2017/Results/2020/M42/Avey.2017.module.M42.2020.results.RData")
load("../Study-1-Avey-2017/Results/2020/M33/Avey.2017.module.M33.2020.results.RData")

# Study 2 - Tsang et al. 2015
load("../Study-2-Tsang-2014/Results/2020/DLDA_top2/Tsang.2014.DLDA.top2.2020.results.RData")
load("../Study-2-Tsang-2014/Results/2020/DLDA_top5/Tsang.2014.DLDA.top5.2020.results.RData")

# Study 3 - Tsang et al. 2015
load("../Study-3-Kotliarov-2020/Results/2020/DESEQ/TGSig/Kotliarov.2020.TGSig.2020.results.DESEQ.RData")
load("../Study-3-Kotliarov-2020/Results/2020/DESEQ/SLE-Sig/Kotliarov.2020.SLE.Sig.2020.results.DESEQ.RData")
load("../Study-3-Kotliarov-2020/Results/2020/DESEQ/IFN-I-DCact/Kotliarov.2020.IFN.I.DCact.2020.results.DESEQ.RData")

# Study 4 - Fourati et al. 2015
load("../Study-4-Fourati-2015/Results/2020/DESEQ/BioAge/Fourati.2015.BioAge.2020.results.DESEQ.RData")
load("../Study-4-Fourati-2015/Results/2020/DESEQ/M1/Fourati.2015.M1.2020.results.DESEQ.RData")
load("../Study-4-Fourati-2015/Results/2020/DESEQ/M1+M16/Fourati.2015.M1.M16.2020.results.DESEQ.RData")
load("../Study-4-Fourati-2015/Results/2020/DESEQ/Naive_bayes/Fourati.2015.NB.2020.results.DESEQ.RData")
load("../Study-4-Fourati-2015/Results/2020/LR/Fourati.2015.LR.2020.results.RData")

# Study 5 - Furman et al. 2013
load("../Study-5-Furman-2013/Results/2020/Age/Furman.2013.Age.2020.results.RData")

# Study 6 - Iulio et al. 2021
load("../Study-6-Iulio-2021/Results/2020/HBV pre-vaccine/Iulio.2021.HBV.transfer.sig.2020.results.RData")
load("../Study-6-Iulio-2021/Results/2020/Influenza pre-vaccine F/Iulio.2021.Inf.F.transfer.sig.2020.results.RData")
load("../Study-6-Iulio-2021/Results/2020/Influenza pre-vaccine M/Iulio.2021.Inf.M.transfer.sig.2020.results.RData")
load("../Study-6-Iulio-2021/Results/2020/TB pre-vaccine/Iulio.2021.TB.transfer.sig.2020.results.RData")

# Study 7 - Fourati et al. 2021
load("../Study-7-Fourati-2021/Results/2020/RF_model/Fourati.2021.RF.2020.results.RData")

# Study 8 - Bartholomeus et al. 2018
load("../Study-8-Bartholomeus-2018/Results/2020/Gene_signature/Bartholomeus.2018.gene.sig.2020.results.RData")
load("../Study-8-Bartholomeus-2018/Results/2020/Naive_bayes/Bartholomeus.2018.NB.2020.results.RData")

# Study 9 - Qui et al. 2018 
load("../Study-9-Qui-2018/Results/2020/Gene_signature/Qui.2018.gene.sig.2020.results.TPM.RData")

# Study 10 - Franco et al. 2013
load("../Study-10-Franco-2013/Results/2020/GeneSig/Franco.2013.gene.sig.2020.results.TPM.RData")

# Combine all results
df.2020.combined <- list(Avey.2017.gene.sig = Avey.2017.gene.sig.2020.results, # Influenza
                         Avey.2017.M54 = Avey.2017.module.M54.2020.results, # Influenza
                         Avey.2017.M42 = Avey.2017.module.M42.2020.results, # Influenza
                         Avey.2017.M33 = Avey.2017.module.M33.2020.results, # Influenza
                         Tsang.2015.DLDA.top2 = Tsang.2014.DLDA.top2.2020.results, # Influenza
                         Tsang.2015.DLDA.top5 = Tsang.2014.DLDA.top5.2020.results, # Influenza
                         Kotliarov.2020.TGSig = Kotliarov.2020.TGSig.2020.results.DESEQ, # Influenza
                         Kotliarov.2020.SLE.Sig = Kotliarov.2020.SLE.Sig.2020.results.DESEQ, # Influenza
                         Kotliarov.2020.IFN.I.DCact = Kotliarov.2020.IFN.I.DCact.2020.results.DESEQ, # Influenza
                         Fourati.2015.BioAge = Fourati.2015.BioAge.2020.results.DESEQ, # HBV
                         Fourati.2015.M1 = Fourati.2015.M1.2020.results.DESEQ, # HBV
                         Fourati.2015.M1.M16 = Fourati.2015.M1.M16.2020.results.DESEQ, # HBV
                         Fourati.2015.NB = Fourati.2015.NB.2020.results.DESEQ, # HBV
                         Fourati.2015.LR = Fourati.2015.LR.2020.results, # HBV
                         Furman.2013.Age = Furman.2013.Age.2020.results, 
                         Iulio.2021.HBV = Iulio.2021.HBV.transfer.sig.2020.results, # HBV
                         Iulio.2021.Influenza.F = Iulio.2021.Inf.F.transfer.sig.2020.results, # Influenza
                         Iulio.2021.Influenza.M = Iulio.2021.Inf.M.transfer.sig.2020.results, # Influenza
                         Iulio.2021.TB = Iulio.2021.TB.transfer.sig.2020.results, # TB (marques)
                         Fourati.2021.RF = Fourati.2021.RF.2020.results, # Multiple vaccines
                         Bartholomeus.2018.gene.sig = Bartholomeus.2018.gene.sig.2020.results, # HBV
                         Bartholomeus.2018.NB = Bartholomeus.2018.NB.2020.results, # HBV
                         Qui.2018.gene.sig = Qui.2018.gene.sig.2020.results.TPM, # HBV
                         Franco.2013.gene.sig = Franco.2013.gene.sig.2020.results.TPM) # Influenza


```

## Load results from all of the prediction methods evaluate on the CMI-PB 2021 dataset

```{r}

############  2021 results ############ 
# Study 1 - Avey et al. 2017
load("../Study-1-Avey-2017/Results/2021/Gene_signature/Avey.2017.gene.sig.2021.results.RData")
load("../Study-1-Avey-2017/Results/2021/M54/Avey.2017.module.M54.2021.results.RData")
load("../Study-1-Avey-2017/Results/2021/M42/Avey.2017.module.M42.2021.results.RData")
load("../Study-1-Avey-2017/Results/2021/M33/Avey.2017.module.M33.2021.results.RData")

# Study 2 - Tsang et al. 2015
load("../Study-2-Tsang-2014/Results/2021/DLDA_top2/Tsang.2014.DLDA.top2.2021.results.RData")
load("../Study-2-Tsang-2014/Results/2021/DLDA_top5/Tsang.2014.DLDA.top5.2021.results.RData")

# Study 3 - Tsang et al. 2015
load("../Study-3-Kotliarov-2020/Results/2021/TGSig/Kotliarov.2020.TGSig.2021.results.RData")
load("../Study-3-Kotliarov-2020/Results/2021/SLE-Sig/Kotliarov.2020.SLE.Sig.2021.results.RData")
load("../Study-3-Kotliarov-2020/Results/2021/IFN-I-DCact/Kotliarov.2020.IFN.I.DCact.2021.results.RData")

# Study 4 - Fourati et al. 2015
load("../Study-4-Fourati-2015/Results/2021/BioAge/Fourati.2015.BioAge.2021.results.RData")
load("../Study-4-Fourati-2015/Results/2021/M1/Fourati.2015.M1.2021.results.RData")
load("../Study-4-Fourati-2015/Results/2021/M1+M16/Fourati.2015.M1.M16.2021.results.RData")
load("../Study-4-Fourati-2015/Results/2021/Naive_bayes/Fourati.2015.NB.2021.results.RData")
load("../Study-4-Fourati-2015/Results/2021/LR/Fourati.2015.LR.2021.results.RData")

# Study 5 - Furman et al. 2013
load("../Study-5-Furman-2013/Results/2021/Age/Furman.2013.Age.2021.results.RData")

# Study 6 - Iulio et al. 2021
load("../Study-6-Iulio-2021/Results/2021/HBV pre-vaccine/Iulio.2021.HBV.transfer.sig.2021.results.RData")
load("../Study-6-Iulio-2021/Results/2021/Influenza pre-vaccine F/Iulio.2021.Inf.F.transfer.sig.2021.results.RData")
load("../Study-6-Iulio-2021/Results/2021/Influenza pre-vaccine M/Iulio.2021.Inf.M.transfer.sig.2021.results.RData")
load("../Study-6-Iulio-2021/Results/2021/TB pre-vaccine/Iulio.2021.TB.transfer.sig.2021.results.RData")

# Study 7 - Fourati et al. 2021
load("../Study-7-Fourati-2021/Results/2021/RF_model/Fourati.2021.RF.2021.results.RData")

# Study 8 - Bartholomeus et al. 2018
load("../Study-8-Bartholomeus-2018/Results/2021/Gene_signature/Bartholomeus.2018.gene.sig.2021.results.RData")
load("../Study-8-Bartholomeus-2018/Results/2021/Naive_bayes/Bartholomeus.2018.NB.2021.results.RData")

# Study 9 - Qui et al. 2018 
load("../Study-9-Qui-2018/Results/2021/Gene_signature/Qui.2018.gene.sig.2021.results.RData")

# Study 10 - Franco et al. 2013
load("../Study-10-Franco-2013/Results/2021/GeneSig/Franco.2013.gene.sig.2021.results.RData")


# Combine all results
df.2021.combined <- list(Avey.2017.gene.sig = Avey.2017.gene.sig.2021.results, # Influenza
                         Avey.2017.M54 = Avey.2017.module.M54.2021.results, # Influenza
                         Avey.2017.M42 = Avey.2017.module.M42.2021.results, # Influenza
                         Avey.2017.M33 = Avey.2017.module.M33.2021.results, # Influenza
                         Tsang.2015.DLDA.top2 = Tsang.2014.DLDA.top2.2021.results, # Influenza
                         Tsang.2015.DLDA.top5 = Tsang.2014.DLDA.top5.2021.results, # Influenza
                         Kotliarov.2020.TGSig = Kotliarov.2020.TGSig.2021.results, # Influenza
                         Kotliarov.2020.SLE.Sig = Kotliarov.2020.SLE.Sig.2021.results, # Influenza
                         Kotliarov.2020.IFN.I.DCact = Kotliarov.2020.IFN.I.DCact.2021.results, # Influenza
                         Fourati.2015.BioAge = Fourati.2015.BioAge.2021.results, # HBV
                         Fourati.2015.M1 = Fourati.2015.M1.2021.results, # HBV
                         Fourati.2015.M1.M16 = Fourati.2015.M1.M16.2021.results, # HBV
                         Fourati.2015.NB = Fourati.2015.NB.2021.results, # HBV
                         Fourati.2015.LR = Fourati.2015.LR.2021.results, # HBV
                         Furman.2013.Age = Furman.2013.Age.2021.results, 
                         Iulio.2021.HBV = Iulio.2021.HBV.transfer.sig.2021.results, # HBV
                         Iulio.2021.Influenza.F = Iulio.2021.Inf.F.transfer.sig.2021.results, # Influenza
                         Iulio.2021.Influenza.M = Iulio.2021.Inf.M.transfer.sig.2021.results, # Influenza
                         Iulio.2021.TB = Iulio.2021.TB.transfer.sig.2021.results, # TB (marques)
                         Fourati.2021.RF = Fourati.2021.RF.2021.results, # Multiple vaccines
                         Bartholomeus.2018.gene.sig = Bartholomeus.2018.gene.sig.2021.results, # HBV
                         Bartholomeus.2018.NB = Bartholomeus.2018.NB.2021.results, # HBV
                         Qui.2018.gene.sig = Qui.2018.gene.sig.2021.results, # HBV
                         Franco.2013.gene.sig = Franco.2013.gene.sig.2021.results) # Influenza


```

## Initialize functions for collect data and plotting

```{r}

collectData <- function(data, metric, outcome="raw", selected.models=NULL,
                        selected.outcomes=NULL){
   
   if(!is.null(selected.models)){
      models <- selected.models
   } else {
      models <- names(data)
   }
   
   df.collect <- data.frame()
   if(tolower(metric) == "spearman"){
      for(model in models){
         
         if(outcome == "raw"){
            
            # Collect the relevant columns from the results
            tmp <- data[[model]][["results"]][, c("isotype_antigen", "corr.value", 
                                                  "corr.p.value", "stars.corr.raw")] %>% 
               distinct() %>% 
               dplyr::rename(stars = stars.corr.raw)
            
            # Name model, create label and save in dataframe
            tmp$model <- model
            tmp$corr.label <- round(tmp$corr.value, 2)
            df.collect <- rbind(df.collect, tmp)
            
         } else if (outcome == "fc"){
            # Collect the relevant columns from the results
            tmp <- data[[model]][["results"]][, c("isotype_antigen", "corr.fc.value", 
                                                  "corr.fc.p.value", "stars.corr.fc")] %>% 
               distinct() %>% 
               dplyr::rename(corr.value = corr.fc.value,
                             corr.p.value = corr.fc.p.value,
                             stars = stars.corr.fc)
            
            # Name model, create label and save in dataframe
            tmp$model <- model
            tmp$corr.label <- round(tmp$corr.value, 2)
            df.collect <- rbind(df.collect, tmp)
         
         }
      }
      df.collect <- df.collect %>% 
         distinct()
      
      if(!is.null(selected.outcomes)){
          df.collect <- df.collect %>% 
              filter(isotype_antigen %in% selected.outcomes)
          
      }
      
      
      # Perform multiple testing correction
      df.collect[["corr.p.value.adj"]] <- p.adjust(df.collect$corr.p.value, 
                                                   method = "BH")
      
      print(summary(df.collect))
      
      return(df.collect)
      
   } else if(tolower(metric) == "auc"){
      
      for(model in models){
         
         if(outcome == "raw"){
            
            # Collect the relevant columns from the results
            tmp <- data[[model]][["results"]][, c("isotype_antigen", "auc.score", 
                                                  "auc.p.value", "stars.auc.raw")] %>% 
               distinct() %>% 
               dplyr::rename(stars = stars.auc.raw)
            
            # Name model, create label and save in dataframe
            tmp$model <- model
            tmp$auc.label <- round(tmp$auc.score, 2)
            df.collect <- rbind(df.collect, tmp)
            
         } else if (outcome == "fc"){
            # Collect the relevant columns from the results
            tmp <- data[[model]][["results"]][, c("isotype_antigen", "auc.score.fc", 
                                                  "auc.p.value.fc", "stars.auc.fc")] %>% 
               distinct() %>% 
               dplyr::rename(auc.score = auc.score.fc,
                             auc.p.value = auc.p.value.fc,
                             stars = stars.auc.fc)
            
            # Name model, create label and save in dataframe
            tmp$model <- model
            tmp$auc.label <- round(tmp$auc.score, 2)
            df.collect <- rbind(df.collect, tmp)
         
         }
      }
      
      df.collect <- df.collect %>% 
         distinct()
      
      if(!is.null(selected.outcomes)){
          df.collect <- df.collect %>% 
              filter(isotype_antigen %in% selected.outcomes)
          
      }
      
      # Perform multiple testing correction
      df.collect[["auc.p.value.adj"]] <- p.adjust(df.collect$auc.p.value, 
                                                   method = "BH")
      print(summary(df.collect))
      
      return(df.collect)
   }
}

plotHeatmap <- function(data, x, y, metric, value, label1, label2){
   
   rwb <- colorRampPalette(colors = c("red", "white", "blue"))
   
   if(tolower(metric) == "spearman"){
      legend.title <- "Spearman's\nCorrelation"
      limits <- c(-1,1)
      custom.colors <- rev(rwb(200))
      # custom.colors <- c("#0000FF", "#3838FF", "#7171FF", "#AAAAFF", "#E2E2FF",
      #                    "#FFFFFF", "#FFFFFF", "#FFE2E2", "#FFAAAA", 
      #                    "#FF7171", "#FF3838", "#FF0000")
   } else if(tolower(metric) == "auc"){
      legend.title <- "AUC score"
      limits <- c(0,1)
      custom.colors <- c("#0000FF", "#3838FF", "#7171FF", "#AAAAFF",
                         "#FFFFFF", "#FFFFFF", "#FFAAAA", 
                         "#FF7171", "#FF3838", "#FF0000")
   }

   plot <-  ggplot(data, aes_string(x = x, y = y, col=value, label=label2)) +
      geom_tile(col="black", fill="white") +
      geom_point(aes_string(size = abs(data[[value]])), shape="square") +
      scale_size(range=c(8, 20), guide=NULL)  + 
      labs(x = NULL, y = NULL, col = legend.title) +
      theme_classic() + 
      coord_fixed() + 
      geom_text(aes_string(label=label1), color = "black", size = 6) +
      geom_text(aes_string(label=label2), color="black", size=7, nudge_y = -0.3) +
      scale_color_gradientn(colors=custom.colors, limits=limits, space = "Lab")  +
      scale_x_discrete(expand=c(0,0)) +
      scale_y_discrete(expand=c(0,0)) +
      theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 15, 
                                       hjust = 1, colour = "black"),
         axis.text.y = element_text(size=15, colour = "black")) +
      geom_vline(xintercept=1:length(unique(data$model))-0.5, 
                 colour="gray", size=0.5) +
      geom_hline(yintercept=1:length(unique(data$isotype_antigen))-0.5, 
                 colour="gray", size=0.5) 
   
   return(plot)
   
}

```

## Heatmaps of 2020 results

```{r}

####### DAY 14 #######
### Spearman's correlation 
df.collect.corr.day14.2020 <- collectData(data=df.2020.combined, metric="spearman", outcome = "raw")
plotHeatmap(df.collect.corr.day14.2020, x="model", y="isotype_antigen", metric = "spearman",
            value="corr.value", label1 = "corr.label", label2 = "stars")
ggsave(filename="2020/Heatmap_Spearman_day14.png", 
       dpi = 400, width = 18, height = 8)

### AUC
df.collect.auc.day14.2020 <- collectData(data=df.2020.combined, metric="AUC", outcome = "raw")
plotHeatmap(df.collect.auc.day14.2020, x="model", y="isotype_antigen", metric = "AUC",
            value="auc.score", label1 = "auc.label", label2 = "stars")
ggsave(filename="2020/Heatmap_AUC_day14.png", 
       dpi = 400, width = 18, height = 8)


####### FOLD-CHANGE #######
### Spearman's correlation 
df.collect.corr.FC.2020 <- collectData(data=df.2020.combined, metric="spearman", outcome = "fc")
plotHeatmap(df.collect.corr.FC.2020, x="model", y="isotype_antigen", metric = "spearman",
            value="corr.value", label1 = "corr.label", label2 = "stars")
ggsave(filename="2020/Heatmap_Spearman_FC.png", 
       dpi = 400, width = 18, height = 8)

### AUC
df.collect.auc.FC.2020 <- collectData(data=df.2020.combined, metric="AUC", outcome = "fc")
plotHeatmap(df.collect.auc.FC.2020, x="model", y="isotype_antigen", metric = "AUC",
            value="auc.score", label1 = "auc.label", label2 = "stars")
ggsave(filename="2020/Heatmap_AUC_FC.png", 
       dpi = 400, width = 18, height = 8)
```

## Heatmaps of 2021 results

```{r}

####### DAY 14 #######
### Spearman's correlation 
df.collect.corr.day14.2021 <- collectData(data=df.2021.combined, metric="spearman", outcome = "raw")
plotHeatmap(df.collect.corr.day14.2021, x="model", y="isotype_antigen", metric = "spearman",
            value="corr.value", label1 = "corr.label", label2 = "stars")
ggsave(filename="2021/Heatmap_Spearman_day14.png", 
       dpi = 400, width = 18, height = 8)

### AUC
df.collect.auc.day14.2021 <- collectData(data=df.2021.combined, metric="AUC", outcome = "raw")
plotHeatmap(df.collect.auc.day14.2021, x="model", y="isotype_antigen", metric = "AUC",
            value="auc.score", label1 = "auc.label", label2 = "stars")
ggsave(filename="2021/Heatmap_AUC_day14.png", 
       dpi = 400, width = 18, height = 8)


####### FOLD-CHANGE #######
### Spearman's correlation 
df.collect.corr.FC.2021 <- collectData(data=df.2021.combined, metric="spearman", 
                               outcome = "fc")
plotHeatmap(df.collect.corr.FC.2021, x="model", y="isotype_antigen", metric = "spearman",
            value="corr.value", label1 = "corr.label", label2 = "stars")
ggsave(filename="2021/Heatmap_Spearman_FC.png", 
       dpi = 400, width = 18, height = 8)

### AUC
df.collect.auc.FC.2021 <- collectData(data=df.2021.combined, metric="AUC", 
                              outcome = "fc")
plotHeatmap(df.collect.auc.FC.2021, x="model", y="isotype_antigen", metric = "AUC",
            value="auc.score", label1 = "auc.label", label2 = "stars")
ggsave(filename="2021/Heatmap_AUC_FC.png", 
       dpi = 400, width = 18, height = 8)
```
## Comparison of results from 2020 to 2021

```{r}

selected.models.outcomes <- c("Avey.2017.gene.sig - IgG4-PT", "Avey.2017.M54 - IgG4-PT",
                              "Furman.2013.Age - IgG4-PT", "Avey.2017.M33 - IgG4-FHA",
                              "Furman.2013.Age - IgG4-FHA", "Tsang.2015.DLDA.top2 - IgG4-FHA",
                              "Kotliarov.2020.TGSig - IgG4-FHA")

# Spearman's correlation day 14 - 2020 vs 2021
df.results.corr.2020 <- df.collect.corr.day14.2020 %>% 
   unite(col = "model_outcome", c("model", "isotype_antigen"), sep = " - ", 
         remove = F) %>% 
   filter(model_outcome %in% selected.models.outcomes) %>% 
   mutate(year = 2020)

df.results.corr.2021 <- df.collect.corr.day14.2021 %>% 
   unite(col = "model_outcome", c("model", "isotype_antigen"), sep = " - ", 
         remove = F) %>% 
   filter(model_outcome %in% selected.models.outcomes) %>% 
   mutate(year = 2021)

df.results.corr.2021$corr.p.value.adj <- p.adjust(df.results.corr.2021$corr.p.value,
                                                  method = "BH")
# View(df.results.corr.2021)
data.corr.day14 <- rbind(df.results.corr.2020, df.results.corr.2021)
data.corr.day14 %>% 
   ggplot(aes(x=factor(year), y=corr.value, group=model_outcome, color=model_outcome)) +
   geom_line(size=0.9) +
   geom_point(size=6, alpha=0.9) +
   labs(x="Year", y="Spearman's correlation", 
        colour="Model and day 14 antibody response") +
   theme_classic() + 
   geom_text_repel(aes(label=stars, group = model_outcome), show.legend = FALSE,
                   size = 30 / .pt, box.padding = 0.7) +
   theme(axis.text.x = element_text(size = 20),
         axis.text.y = element_text(size = 20),
         legend.text = element_text(size = 12),
         legend.title = element_text(size = 14),
         axis.title.x = element_text(size = 20),
         axis.title.y = element_text(size = 20),
         legend.box.just = "left",
         legend.justification = c(1,0),
         legend.position = c(0.98,0.7)) + 
   scale_x_discrete() +
   scale_y_continuous(limits = c(-1, 1)) + 
   geom_hline(yintercept = 0, linetype='dashed', size=1) + 
   annotate("text", x=0.55, y=0, vjust = -1, label = "Random", size=5)

ggsave(filename="2020_vs_2021/Comparing_2020_and_2021_corr_day14.png", 
       dpi = 400, width = 8, height = 8)

# AUC day 14 - 2020 vs 2021
df.results.AUC.2020 <- df.collect.auc.day14.2020 %>% 
   unite(col = "model_outcome", c("model", "isotype_antigen"), sep = " - ", 
         remove = F) %>% 
   filter(model_outcome %in% selected.models.outcomes) %>% 
   mutate(year = 2020)

df.results.AUC.2021 <- df.collect.auc.day14.2021 %>% 
   unite(col = "model_outcome", c("model", "isotype_antigen"), sep = " - ", 
         remove = F) %>% 
   filter(model_outcome %in% selected.models.outcomes) %>% 
   mutate(year = 2021)

df.results.AUC.2021$auc.p.value.adj <- p.adjust(df.results.AUC.2021$auc.p.value,
                                                  method = "BH")

# View(df.results.AUC.2021)
library(ggrepel)
data.AUC.day14 <- rbind(df.results.AUC.2020, df.results.AUC.2021)
data.AUC.day14 %>% 
   ggplot(aes(x=factor(year), y=auc.score, group=model_outcome, color=model_outcome)) +
   geom_line(size=0.9) +
   geom_point(size=6, alpha=0.9) +
   labs(x="Year", y="AUC", 
        colour="Model and day 14 antibody response") +
   theme_classic() + 
   geom_text_repel(aes(label=stars, group = model_outcome), show.legend = FALSE,
                   size = 30 / .pt, box.padding = 0.6) +
   theme(axis.text.x = element_text(size = 20),
         axis.text.y = element_text(size = 20),
         legend.text = element_text(size = 12),
         legend.title = element_text(size = 14),
         axis.title.x = element_text(size = 20),
         axis.title.y = element_text(size = 20),
         legend.box.just = "left",
         legend.justification = c(1,0),
         legend.position = c(0.5,0.1)) + 
   scale_x_discrete() +
   scale_y_continuous(limits = c(0, 1)) + 
   geom_hline(yintercept = 0.5, linetype='dashed', size=1) + 
   annotate("text",x =0.55, y=0.5, vjust = -1, label = "Random", size=5)


ggsave(filename="2020_vs_2021/Comparing_2020_and_2021_AUC_day14.png", 
       dpi = 400, width = 8, height = 8)


 # Spearman's correlation fold-change - 2020 vs 2021

selected.models.outcomes <- c("Avey.2017.M42 - IgG-PT","Tsang.2015.DLDA.top2 - IgG-PRN",
                              "Iulio.2021.Influenza.M - IgG1-PT")

df.results.corr.FC.2020 <- df.collect.corr.FC.2020 %>% 
   unite(col = "model_outcome", c("model", "isotype_antigen"), sep = " - ", 
         remove = F) %>% 
   filter(model_outcome %in% selected.models.outcomes) %>% 
   mutate(year = 2020)

df.results.corr.FC.2021 <- df.collect.corr.FC.2021 %>% 
   unite(col = "model_outcome", c("model", "isotype_antigen"), sep = " - ", 
         remove = F) %>% 
   filter(model_outcome %in% selected.models.outcomes) %>% 
   mutate(year = 2021)

data.corr.FC <- rbind(df.results.corr.FC.2020, df.results.corr.FC.2021)
data.corr.FC %>% 
   ggplot(aes(x=factor(year), y=corr.value, group=model_outcome, color=model_outcome)) +
   geom_line(size=0.9) +
   geom_point(size=6, alpha=0.9) +
   labs(x="Year", y="Spearman's correlation", 
        colour="Model and fold-change antibody response") +
   theme_classic() + 
   geom_text_repel(aes(label=stars, group = model_outcome), show.legend = FALSE,
                   size = 30 / .pt, box.padding = 0.6) + 
   theme(axis.text.x = element_text(size = 20),
         axis.text.y = element_text(size = 20),
         legend.text = element_text(size = 12),
         legend.title = element_text(size = 14),
         axis.title.x = element_text(size = 20),
         axis.title.y = element_text(size = 20),
         legend.box.just = "left",
         legend.justification = c(1,0),
         legend.position = c(0.98,0.1)) + 
   scale_x_discrete() +
   scale_y_continuous(limits = c(-1, 1)) + 
   geom_hline(yintercept = 0, linetype='dashed', size=1) + 
   annotate("text", x=0.55, y=0, vjust = -1, label = "Random", size=5)

ggsave(filename="2020_vs_2021/Comparing_2020_and_2021_corr_FC.png", 
       dpi = 400, width = 8, height = 8)

# AUC day 14 - 2020 vs 2021
df.results.AUC.FC.2020 <- df.collect.auc.FC.2020 %>% 
   unite(col = "model_outcome", c("model", "isotype_antigen"), sep = " - ", 
         remove = F) %>% 
   filter(model_outcome %in% selected.models.outcomes) %>% 
   mutate(year = 2020)

df.results.AUC.FC.2021 <- df.collect.auc.FC.2021 %>% 
   unite(col = "model_outcome", c("model", "isotype_antigen"), sep = " - ", 
         remove = F) %>% 
   filter(model_outcome %in% selected.models.outcomes) %>% 
   mutate(year = 2021)

data.AUC.FC <- rbind(df.results.AUC.FC.2020, df.results.AUC.FC.2021)
data.AUC.FC %>% 
   ggplot(aes(x=factor(year), y=auc.score, group=model_outcome, color=model_outcome)) +
   geom_line(size=0.9) +
   geom_point(size=6, alpha=0.9) +
   labs(x="Year", y="AUC", 
        colour="Model and fold-change antibody response") +
   theme_classic() + 
   geom_text_repel(aes(label=stars, group = model_outcome), show.legend = FALSE,
                   size = 30 / .pt, box.padding = 0.6) + 
   theme(axis.text.x = element_text(size = 20),
         axis.text.y = element_text(size = 20),
         legend.text = element_text(size = 12),
         legend.title = element_text(size = 14),
         axis.title.x = element_text(size = 20),
         axis.title.y = element_text(size = 20),
         legend.box.just = "left",
         legend.justification = c(1,0),
         legend.position = c(0.98,0.7)) + 
   scale_x_discrete() +
   scale_y_continuous(limits = c(0, 1)) + 
   geom_hline(yintercept = 0.5, linetype='dashed', size=1) + 
   annotate("text", x=0.55, y=0.5, vjust = -1, label = "Random", size=5)

ggsave(filename="2020_vs_2021/Comparing_2020_and_2021_AUC_FC.png", 
       dpi = 400, width = 8, height = 8)

```
